Repository HandyBus/handybus-admin-web-latest, pull requests merged in 2025-05, with the labels that each got.

#202 feat: 공지사항 api 연결
  src/app/announcements/[announcementId]/edit/page.tsx
  src/app/announcements/[announcementId]/page.tsx
  src/app/announcements/components/AnnouncementFilter.tsx
  src/app/announcements/hooks/useAnnouncementFilter.ts
  src/app/announcements/new/page.tsx
  src/app/announcements/page.tsx
  src/app/announcements/table.type.tsx
  src/app/notices/[noticeId]/edit/page.tsx
  src/app/notices/[noticeId]/page.tsx
  src/app/notices/new/page.tsx
  src/app/notices/page.tsx
  src/app/notices/table.type.tsx
  src/components/announcement/AnnouncementForm.tsx
  src/components/layout/Breadcrumbs.tsx
  src/components/layout/Nav.tsx
  src/services/core.service.ts
  src/types/announcement.type.ts
Labels: ✨ feat

#203 release
  package-lock.json
  package.json
  src/app/announcements/[announcementId]/edit/page.tsx
  src/app/announcements/[announcementId]/page.tsx
  src/app/announcements/components/AnnouncementFilter.tsx
  src/app/announcements/hooks/useAnnouncementFilter.ts
  src/app/announcements/new/page.tsx
  src/app/announcements/page.tsx
  src/app/announcements/table.type.tsx
  src/app/events/table.type.tsx
  src/components/announcement/AnnouncementForm.tsx
  src/components/layout/Breadcrumbs.tsx
  src/components/layout/Nav.tsx
  src/services/config.ts
  src/services/core.service.ts
  src/types/announcement.type.ts
Labels: 🔖 release

#204 fix: 행사 dailyEvents 정렬 이슈 해결
  src/app/events/page.tsx
  src/app/events/table.type.tsx
Labels: 🐛 fix

#205 release
  src/app/events/page.tsx
  src/app/events/table.type.tsx
Labels: 🔖 release

#206 feat: shuttleRoute 폼에 role 추가, v3 api 대응
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/extractHubs.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/extractSortedShuttleHubs.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/utils/extractHubs.ts
  src/services/shuttleRoute.service.ts
  src/types/shuttleRoute.type.ts
Labels: ✨ feat

#207 feat: 일자별 행사의 수요조사 종료 시간 반영
  src/app/events/[eventId]/edit/form.type.ts
  src/app/events/new/form.type.ts
  src/types/event.type.ts
Labels: ✨ feat

#208 fix: resevationViewEntity hasReview 필드를 reviewId 로 변경
  src/types/reservation.type.ts
Labels: 🐛 fix

#209 fix: 쿠폰 날짜 선택시 UTC로 반영 안되던 이슈 해결
  src/app/coupons/new/page.tsx
Labels: 🐛 fix

#211 feat: 7,9인승 스타리아 추가
  src/types/shuttleBus.type.ts
  src/utils/stringifier.util.ts
Labels: ✨ feat

#213 feat: 7,9인승 스타리아 추가 (direct to main)
  src/types/shuttleBus.type.ts
  src/utils/stringifier.util.ts
Labels: ✨ feat
