Repository HandyBus/handybus-admin-web-latest, pull requests merged in 2025-06, with the labels that each got.

#216 design: 기본 마크다운 서식 반영
  package-lock.json
  package.json
  src/app/announcements/page.tsx
  tailwind.config.ts
Labels: 🎨 design

#219 feat: 노선 상태 변경 기능 추가
  src/app/events/[eventId]/dates/[dailyEventId]/EditRouteStatusDialog.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/form.type.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx
  src/services/shuttleRoute.service.ts
Labels: ✨ feat

#222 release: V2
  package-lock.json
  package.json
  src/app/announcements/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/EditRouteStatusDialog.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/form.type.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx
  src/app/reservations/[reservationId]/types/reservationMeta.type.ts
  src/app/reservations/components/RefundTypeInput.tsx
  src/app/reservations/components/RequestRefundDialog.tsx
  src/app/reservations/table.type.tsx
  src/services/payment.service.ts
  src/services/shuttleRoute.service.ts
  src/types/payment.type.ts
  src/types/reservation.type.ts
  src/utils/stringifier.util.ts
  tailwind.config.ts
Labels: 🔖 release

#231 design: 수요조사 대시보드에 관련 행사 정보 표기 (Suspense 적용)
  src/app/events/[eventId]/dates/[dailyEventId]/demands/page.tsx
  src/services/event.service.ts
Labels: 🎨 design

#235 fix: 테이블 용어 변경
  src/app/reservations/[reservationId]/types/payment.table.type.ts
Labels: 🐛 fix

#240 feat: 유요한 예약수에 인원수를 함께 표기
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/ReservationTable.tsx
Labels: ✨ feat

#241 release: V2
  src/app/(home)/components/UserFunnelChart.tsx
  src/app/announcements/new/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Table.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/ReservationTable.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/table.type.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/utils/transformToShuttleRouteRequest.ts
  src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx
  src/app/events/new/form.type.ts
  src/app/events/page.tsx
  src/app/events/pin/edit/page.tsx
  src/app/events/pin/page.tsx
  src/app/events/pin/table.type.tsx
  src/app/events/table.type.tsx
  src/app/feedbacks/page.tsx
  src/app/feedbacks/table.type.ts
  src/app/reservations/[reservationId]/types/payment.table.type.ts
  src/app/reservations/components/CancelReservationDialog.tsx
  src/app/reservations/page.tsx
  src/app/reservations/table.type.tsx
  src/components/layout/Breadcrumbs.tsx
  src/components/layout/Nav.tsx
  src/components/table/BaseTable.tsx
  src/services/config.ts
  src/services/event.service.ts
  src/services/feedback.service.ts
  src/services/reservation.service.ts
  src/types/event.type.ts
  src/types/feedback.type.ts
  src/types/shuttleRoute.type.ts
Labels: 🔖 release

#243 release: V2
  src/services/feedback.service.ts
Labels: 🔖 release
