Repository HandyBus/handybus-admin-web-latest, pull requests merged in 2025-08, with the labels that each got.

#280 feat: 공지방 링크 추가/수정하기
  src/app/events/[eventId]/dates/[dailyEventId]/EditDailyEventOpenChatUrl.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/events/table.type.tsx
  src/components/link/BlueLink.tsx
  src/types/event.type.ts
Labels: ✨ feat

#284 feat: 빈자리 요청 갯수 확인하기 및 데브모드 파비콘 추가
  public/favicons/favicon-dev.png
  public/favicons/favicon.ico
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx
  src/app/layout.tsx
  src/services/shuttleRoute.service.ts
  src/types/shuttleRoute.type.ts
Labels: ✨ feat

#288 design: 텍스트 색상 수정
  src/app/coupons/table.type.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/components/CalculatedDataAndMapView.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx
  src/app/events/page.tsx
Labels: 🎨 design

#290 fix: 기존 디자인 시스템 색상 클래스 수정
  src/app/announcements/[announcementId]/page.tsx
  src/app/announcements/components/AnnouncementFilter.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Map.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/demands/map.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/demands/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/PriceSectionEarlyBirdType.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/ShuttleRouteHubItems.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/BusTable.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/ReservationTable.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/table.type.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
  src/app/events/components/EventFilter.tsx
  src/app/locations/components/RegionHubFilter.tsx
  src/app/reservations/table.type.tsx
  src/app/users/[userId]/components/reservations-table/table.type.tsx
  src/app/users/components/UserFilter.tsx
  src/components/chart/ChartBox.tsx
  src/components/chart/CustomBarChart.tsx
  src/components/table/BaseTable.tsx
  src/components/table/VerticalTable.tsx
Labels: 🐛 fix

#291 release: V2
  src/app/announcements/[announcementId]/page.tsx
  src/app/announcements/components/AnnouncementFilter.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Map.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/demands/map.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/demands/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/PriceSectionEarlyBirdType.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/ShuttleRouteHubItems.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/BusTable.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/ReservationTable.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/table.type.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
  src/app/events/components/EventFilter.tsx
  src/app/locations/components/RegionHubFilter.tsx
  src/app/reservations/table.type.tsx
  src/app/users/[userId]/components/reservations-table/table.type.tsx
  src/app/users/components/UserFilter.tsx
  src/components/chart/ChartBox.tsx
  src/components/chart/CustomBarChart.tsx
  src/components/table/BaseTable.tsx
  src/components/table/VerticalTable.tsx
Labels: 🔖 release

#295 fix: 노선 소요시간 계산값 폼 미반영 버그 수정
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/components/single-route-form/HubsSection.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/utils/validateShuttleRouteData.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/calculateRoute.ts
Labels: 🐛 fix

#296 fix: 소요시간 form 값과 input 값 동기화
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/validateShuttleRouteData.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/components/MultiRouteForm.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/components/single-route-form/HubsSection.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/calculateRoute.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/roundNearestFiveMinutes.util.ts
Labels: 🐛 fix

#294 fix: 차량 대금에 차량 수 곱셈 계산
  src/app/events/[eventId]/sales/components/SalesRow.tsx
  src/app/events/[eventId]/sales/components/SalesTable.tsx
Labels: 🐛 fix

#298 feat: 공지방 필수 생성 비활성화
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
Labels: ✨ feat

#303 feat: 행사 상세 이미지 칼럼 반영
  src/app/events/[eventId]/edit/page.tsx
  src/app/events/[eventId]/table.type.tsx
  src/app/events/new/page.tsx
  src/app/events/page.tsx
  src/components/input/ImageFileInput.tsx
  src/types/event.type.ts
Labels: ✨ feat

#304 feat: 노선 개설 관련 알림톡 발송 기능
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx
  src/app/events/[eventId]/table.type.tsx
  src/services/shuttleRoute.service.ts
  src/services/solapi.service.ts
Labels: ✨ feat

#307 design: 매출 대시보드에 노선명 필드에 y scroll 가리기 및 텍스트 짤리는 이슈해결
  src/app/events/[eventId]/sales/components/SalesRow.tsx
  src/app/events/[eventId]/sales/components/SalesTable.tsx
Labels: 🎨 design

#308 fix: 핸디팟 노선 개설 도착지 setter 함수 수정
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
Labels: 🐛 fix

#309 release: V2
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
  src/app/events/[eventId]/sales/components/SalesRow.tsx
  src/app/events/[eventId]/sales/components/SalesTable.tsx
  src/app/statistics/users/components/SocialLoginChart.tsx
  src/app/statistics/users/page.tsx
  src/types/dashboard.type.ts
Labels: 🔖 release

#312 fix: 일자별 탑승 정보 알림톡 전송 순차적 처리
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
Labels: 🐛 fix
