Repository HandyBus/handybus-admin-web-latest, pull requests merged in 2025-03, with the labels that each got.

#167 feat: add pr labeler 추가
  .github/workflows/pr-labeler.yml
Labels: ✨ feature

#168 feat: 유저 참여 현황 차트
  src/app/(home)/components/DemandCountChart.tsx
  src/app/(home)/components/ReservationPassengerCountChart.tsx
  src/app/(home)/components/ReviewCountChart.tsx
  src/app/(home)/components/SalesCountChart.tsx
  src/app/(home)/components/UserCountChart.tsx
  src/app/(home)/components/UserFunnelChart.tsx
  src/app/(home)/page.tsx
  src/app/statistics/users/components/AgeRangeChart.tsx
  src/app/statistics/users/components/GenderChart.tsx
  src/app/statistics/users/components/MarketingConsentChart.tsx
  src/app/statistics/users/components/SocialLoginChart.tsx
  src/app/statistics/users/page.tsx
  src/components/chart/ChartBox.tsx
  src/components/chart/CustomBarChart.tsx
  src/components/chart/CustomLineChart.tsx
  src/components/chart/CustomPieChart.tsx
  src/components/chart/chart.const.ts
  src/components/chart/chart.util.ts
  src/services/reservation.service.ts
  src/types/dashboard.type.ts
Labels: ✨ feature

#169 release
  .github/workflows/pr-labeler.yml
  src/app/(home)/components/DemandCountChart.tsx
  src/app/(home)/components/ReservationPassengerCountChart.tsx
  src/app/(home)/components/ReviewCountChart.tsx
  src/app/(home)/components/SalesCountChart.tsx
  src/app/(home)/components/UserCountChart.tsx
  src/app/(home)/components/UserFunnelChart.tsx
  src/app/(home)/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Map.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routeDemand.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx
  src/app/reservations/[reservationId]/types/route.table.type.ts
  src/app/statistics/users/components/AgeRangeChart.tsx
  src/app/statistics/users/components/GenderChart.tsx
  src/app/statistics/users/components/MarketingConsentChart.tsx
  src/app/statistics/users/components/SocialLoginChart.tsx
  src/app/statistics/users/page.tsx
  src/components/chart/ChartBox.tsx
  src/components/chart/CustomBarChart.tsx
  src/components/chart/CustomLineChart.tsx
  src/components/chart/CustomPieChart.tsx
  src/components/chart/chart.const.ts
  src/components/chart/chart.util.ts
  src/components/input/CoordInput.tsx
  src/components/input/ShuttleRouteInput.tsx
  src/components/layout/Nav.tsx
  src/components/toast-container/ToastContainer.css
  src/services/hub.service.ts
  src/services/reservation.service.ts
  src/services/shuttleRoute.service.ts
  src/types/dashboard.type.ts
  src/types/region.type.ts
  src/types/reservation.type.ts
  src/types/shuttleRoute.type.ts
  src/types/user.type.ts
Labels: 🔖 release

#170 fix: 유저 현황 차트 값이 올바르게 반영되도록 수정
  src/app/(home)/components/UserFunnelChart.tsx
Labels: 🐛 fix

#171 release
  src/app/(home)/components/UserFunnelChart.tsx
Labels: 🔖 release

#173 release
  src/app/(home)/components/UserFunnelChart.tsx
Labels: 🔖 release

#175 fix: 수요조사 카운트 api 옵션 미반영 수정
  src/services/demand.service.ts
  src/services/review.service.ts
Labels: 🐛 fix

#177 fix: 예약 탑승객 수에 취소한 예약 탑승객 수 합산
  src/app/(home)/components/ReservationPassengerCountChart.tsx
  src/components/chart/ChartBox.tsx
Labels: 🐛 fix

#179 release
  src/app/(home)/components/ReservationPassengerCountChart.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx
  src/components/chart/ChartBox.tsx
Labels: 🔖 release

#180 fix: 카카오 api의 단 시간 내 많은 호출 방지로 인한 클러스토 미표시 수정
  src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Map.tsx
Labels: 🐛 fix

#181 feat: 정류장 핀 로드 이슈 해결 및 기능 개선
  src/app/locations/map/components/hubsMap.tsx
  src/app/locations/map/createOverlayHTML.util.ts
  src/app/locations/map/page.tsx
  src/app/locations/new/page.tsx
  src/components/input/CoordInput.tsx
Labels: ✨ feat

#182 feat: 노선 매출 정보 표시
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/table.type.tsx
  src/types/shuttleBus.type.ts
  src/utils/date.util.ts
Labels: ✨ feat

#184 release
  .github/workflows/pr-labeler.yml
  src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Map.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/table.type.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/conform.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/form.type.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/calculateRoute.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/roundNearestFiveMinutes.util.ts
  src/app/locations/map/components/hubsMap.tsx
  src/app/locations/map/createOverlayHTML.util.ts
  src/app/locations/map/page.tsx
  src/app/locations/new/page.tsx
  src/components/input/CoordInput.tsx
  src/components/input/HubInput.tsx
  src/services/kakaomoblility.service.ts
  src/types/kakaomoblity.type.ts
  src/types/shuttleBus.type.ts
  src/utils/date.util.ts
Labels: 🔖 release

#185 feat: 장소 - 지도 인터렉션 기능 추가 및 개선
  src/app/locations/[regionId]/hubs/[hubId]/edit/page.tsx
  src/app/locations/components/MapGuides.tsx
  src/app/locations/components/MapGuidesAtNewEditPage.tsx
  src/app/locations/map/components/hubsMap.tsx
  src/app/locations/map/page.tsx
  src/app/locations/new/page.tsx
  src/components/input/CoordInput.tsx
  src/utils/region.util.ts
Labels: ✨ feat

#186 refactor: 코드 개선 및 alert 3번 뜨는 것 방지 (+ Testing 에 대한 고심)
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/calculateRoute.ts
Labels: 🔄 refactor

#188 fix: handleFillUnassignedReservation 에서 남은 좌석수가 제대로 계산되지 않던 이슈 해결
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/BusTable.tsx
Labels: 🐛 fix

#187 fix: 경로소요시간 계산하기
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/calculateRoute.ts
Labels: 🐛 fix

#189 release
  .github/workflows/pr-labeler.yml
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/BusTable.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/calculateRoute.ts
  src/app/locations/[regionId]/hubs/[hubId]/edit/page.tsx
  src/app/locations/components/MapGuides.tsx
  src/app/locations/components/MapGuidesAtNewEditPage.tsx
  src/app/locations/map/components/hubsMap.tsx
  src/app/locations/map/page.tsx
  src/app/locations/new/page.tsx
  src/components/input/CoordInput.tsx
  src/utils/region.util.ts
Labels: 🔖 release
