Repository HandyBus/handybus-admin-web-latest, pull requests merged in 2025-07, with the labels that each got.

#246 release: V2
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/page.tsx
Labels: 🔖 release

#244 feat: 핸디팟 노선 묶음 생성
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/hooks/usePostHandyPartyRoutes.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
  src/app/locations/[regionId]/hubs/[hubId]/edit/page.tsx
  src/app/locations/components/RegionHubFilter.tsx
  src/app/locations/hooks/useRegionHubFilter.tsx
  src/app/locations/location.type.ts
  src/app/locations/new/page.tsx
  src/app/locations/table.type.tsx
  src/constants/common.ts
  src/constants/handyPartyArea.const.ts
  src/constants/handyPartyPriceTable.const.ts
  src/services/hub.service.ts
  src/types/hub.type.ts
  src/types/shuttleRoute.type.ts
  src/types/shuttleStop.type.ts
Labels: ✨ feat

#249 release: V2
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/hooks/usePostHandyPartyRoutes.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
  src/app/locations/[regionId]/hubs/[hubId]/edit/page.tsx
  src/app/locations/components/RegionHubFilter.tsx
  src/app/locations/hooks/useRegionHubFilter.tsx
  src/app/locations/location.type.ts
  src/app/locations/new/page.tsx
  src/app/locations/table.type.tsx
  src/constants/common.ts
  src/constants/handyPartyArea.const.ts
  src/constants/handyPartyPriceTable.const.ts
  src/services/hub.service.ts
  src/types/hub.type.ts
  src/types/shuttleRoute.type.ts
  src/types/shuttleStop.type.ts
Labels: 🔖 release

#251 release: V2
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/table.type.tsx
  src/app/reservations/[reservationId]/types/reservationMeta.type.ts
  src/app/reservations/page.tsx
  src/types/reservation.type.ts
Labels: 🔖 release

#247 feat: 택시팟 최적 노선 설계기
  src/app/events/[eventId]/dates/[dailyEventId]/optimizer/components/CalculatedDataAndMapView.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/optimizer/components/EventPlaceSelect.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/optimizer/components/HandyPartyMap.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/optimizer/hooks/useCalculateOptimizedRoute.ts
  src/app/events/[eventId]/dates/[dailyEventId]/optimizer/hooks/useDrag.ts
  src/app/events/[eventId]/dates/[dailyEventId]/optimizer/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/optimizer/types/optimizer.type.ts
  src/app/events/[eventId]/dates/[dailyEventId]/optimizer/utils/optimizer.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/optimizer/utils/parseInputData.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/calculateRoute.ts
  src/services/kakaomoblility.service.ts
Labels: ✨ feat

#252 chore: 핸디팟 권역 추가
  src/constants/handyPartyArea.const.ts
  src/constants/handyPartyPriceTable.const.ts
Labels: 🧹 chore

#253 feat: 스포츠 행사 타입 반영
  src/app/events/new/page.tsx
  src/types/event.type.ts
Labels: ✨ feat

#255 fix: 핸디팟 노선 생성 기본값 수정
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
Labels: 🐛 fix

#258 release: V2
  src/app/reservations/page.tsx
  src/app/users/[userId]/components/reservations-table/table.type.tsx
Labels: 🔖 release

#260 feat: 행사 상태 변경
  src/app/events/[eventId]/edit/page.tsx
Labels: ✨ feat

#261 release: V2
  src/app/events/[eventId]/edit/page.tsx
Labels: 🔖 release

#263 feat: 예약 테이블 UI 통일
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/table.type.tsx
  src/app/reservations/components/CancelReservationDialog.tsx
  src/app/reservations/table.type.tsx
  src/components/dialog/EditHandyStatusDialog.tsx
  src/components/link/BlueButton.tsx
  src/types/event.type.ts
Labels: ✨ feat, 🎨 design

#265 feat: 특정 행사에 대해서만 사용 가능한 쿠폰 조회 및 생성
  src/app/coupons/new/page.tsx
  src/app/coupons/table.type.tsx
  src/app/events/[eventId]/page.tsx
  src/app/events/[eventId]/table.type.tsx
  src/services/coupon.service.ts
  src/types/coupon.type.ts
Labels: ✨ feat

#268 feat: KSPO DOME 단가표
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
  src/constants/handyPartyPriceTable.const.ts
Labels: ✨ feat

#270 feat: 공지사항 생성 시 이미지 업로드 기능
  src/app/banners/components/BannerImageFileInput.tsx
  src/components/announcement/AnnouncementForm.tsx
  src/components/input/ImageFileInput.tsx
  src/services/core.service.ts
Labels: ✨ feat

#271 release: V2
  src/app/banners/components/BannerImageFileInput.tsx
  src/components/announcement/AnnouncementForm.tsx
  src/components/input/ImageFileInput.tsx
  src/services/core.service.ts
Labels: 🔖 release

#272 feat: 일자별 핸디팟 승객 자동 배차하기
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/components/CalculatedDataAndMapView.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/components/EventPlaceSelect.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/components/HandyPartyMap.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/hooks/useCalculateOptimizedRoute.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/hooks/useDrag.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/types/optimizer.type.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/utils/optimizer.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/utils/parseInputData.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/components/CalculatedDataAndMapView.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/components/EventPlaceSelect.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/components/HandyPartyMap.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/constants/handyPartyOptimizer.constant.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/hooks/useDrag.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/hooks/useExcelDownload.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/hooks/useHandyPartyReservations.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/hooks/useOptimalRouteCalculation.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/types/handyPartyOptimizer.type.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/utils/optimizer.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/hooks/useCreateCurrentTimeLog.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/hooks/useEventInfo.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/hooks/useInputText.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/hooks/useVehicleAutoAssignment.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/types/vehicleAutoAssignment.type.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/utils/parseInputData.ts
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
Labels: ✨ feat

#273 fix: 노선 수정 시 수정된 값만 포함
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/EditForm.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/transformToShuttleRouteRequest.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/validateShuttleRouteData.ts
  src/types/shuttleRoute.type.ts
Labels: 🐛 fix

#274 release: V2
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/components/CalculatedDataAndMapView.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/components/EventPlaceSelect.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/components/HandyPartyMap.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/hooks/useCalculateOptimizedRoute.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/hooks/useDrag.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/types/optimizer.type.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/utils/optimizer.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/utils/parseInputData.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/components/CalculatedDataAndMapView.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/components/EventPlaceSelect.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/components/HandyPartyMap.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/constants/handyPartyOptimizer.constant.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/hooks/useDrag.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/hooks/useExcelDownload.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/hooks/useHandyPartyReservations.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/hooks/useOptimalRouteCalculation.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/types/handyPartyOptimizer.type.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/utils/optimizer.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/hooks/useCreateCurrentTimeLog.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/hooks/useEventInfo.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/hooks/useInputText.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/hooks/useVehicleAutoAssignment.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/types/vehicleAutoAssignment.type.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/vehicle-auto-assignment/utils/parseInputData.ts
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/EditForm.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/transformToShuttleRouteRequest.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/validateShuttleRouteData.ts
  src/types/shuttleRoute.type.ts
Labels: 🔖 release

#275 feat: 수요조사 리워드 쿠폰 생성
  src/app/coupons/new/page.tsx
  src/app/coupons/table.type.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
  src/app/events/new/page.tsx
  src/components/input/EventInput.tsx
  src/services/event.service.ts
  src/types/coupon.type.ts
  src/utils/coupon.util.ts
Labels: ✨ feat

#277 feat: 실명제 도입
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/table.type.tsx
  src/app/reservations/[reservationId]/types/account.table.type.ts
  src/app/reservations/components/ReservationFilter.tsx
  src/app/reservations/hooks/userReservationFilter.ts
  src/app/reservations/table.type.tsx
  src/app/users/[userId]/components/reservations-table/table.type.tsx
  src/app/users/[userId]/components/user-table/table.type.tsx
  src/app/users/components/UserFilter.tsx
  src/app/users/hooks/useUserFilter.tsx
  src/app/users/table.type.tsx
  src/services/reservation.service.ts
  src/services/user.service.ts
  src/types/reservation.type.ts
  src/types/user.type.ts
Labels: ✨ feat
