Repository HandyBus/handybus-admin-web-latest, pull requests merged in 2025-09, with the labels that each got.

#317 feat: 예약 취소 통계
  src/app/(home)/components/CancellationCountChart.tsx
  src/app/(home)/page.tsx
  src/services/reservation.service.ts
  src/types/dashboard.type.ts
Labels: ✨ feat

#318 release: V2
  .gitignore
  package-lock.json
  package.json
  src/app/(home)/components/CancellationCountChart.tsx
  src/app/(home)/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/hooks/useExportPassengerList.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/refund/page.tsx
  src/services/reservation.service.ts
  src/types/dashboard.type.ts
  src/types/shuttleRoute.type.ts
  src/utils/csvProcessor.util.ts
Labels: 🔖 release

#319 release: V2
  src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Map.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/demands/map.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/demands/table.type.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer-paste/utils/optimizer.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/utils/optimizer.util.ts
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/PriceSectionEarlyBirdType.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/PriceSectionRegularType.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/ShuttleRouteHubItems.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/ShuttleRouteHubSection.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/validateShuttleRouteData.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/page.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/table.type.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/components/single-route-form/HubsSection.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/components/single-route-form/PriceSection.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/form.type.ts
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/hooks/usePostHandyPartyRoutes.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/routes/new/utils/validateShuttleRouteData.ts
  src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx
  src/app/statistics/demands/map.util.ts
  src/types/shuttleRoute.type.ts
  src/utils/stringifier.util.ts
Labels: 🔖 release

#320 fix: 탑승자 명단 추출 내 예외 처리 수정
  src/app/events/[eventId]/dates/[dailyEventId]/hooks/useExportPassengerList.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
Labels: 🐛 fix

#321 release: V2
  src/app/events/[eventId]/dates/[dailyEventId]/hooks/useExportPassengerList.tsx
  src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
Labels: 🔖 release

#323 feat: 장소 추가/수정하기에 로드뷰 추가
  src/app/locations/components/Roadview.tsx
  src/components/input/CoordInput.tsx
Labels: ✨ feat

#325 release: V2
  src/app/events/[eventId]/dates/[dailyEventId]/hooks/useExportPassengerList.tsx
  src/app/locations/components/Roadview.tsx
  src/components/input/CoordInput.tsx
Labels: 🔖 release

#331 release: V2
  src/app/locations/[regionId]/hubs/[hubId]/edit/page.tsx
  src/app/locations/components/Roadview.tsx
  src/app/locations/new/page.tsx
  src/components/input/CoordInput.tsx
Labels: 🔖 release

#334 release: V2
  src/app/locations/[regionId]/hubs/[hubId]/edit/form.type.ts
  src/app/locations/[regionId]/hubs/[hubId]/edit/page.tsx
  src/app/locations/components/Roadview.tsx
  src/app/locations/new/form.type.ts
  src/app/locations/new/page.tsx
  src/components/input/CoordInput.tsx
  src/types/hub.type.ts
Labels: 🔖 release

#336 release: V2
  src/app/events/[eventId]/dates/[dailyEventId]/demands/hooks/useExportDemandRequestersList.ts
  src/app/events/[eventId]/dates/[dailyEventId]/demands/page.tsx
  src/app/reviews/components/FilterButton.tsx
  src/app/reviews/components/ImageModal.tsx
  src/app/reviews/components/Rating.tsx
  src/app/reviews/components/RatingForm.tsx
  src/app/reviews/components/ReviewItem.tsx
  src/app/reviews/components/ReviewList.tsx
  src/app/reviews/components/ReviewProperty.tsx
  src/app/reviews/components/ReviewStatistics.tsx
  src/app/reviews/components/UserProfile.tsx
  src/app/reviews/icons/artist.svg
  src/app/reviews/icons/heart.svg
  src/app/reviews/icons/locate.svg
  src/app/reviews/icons/review.svg
  src/app/reviews/icons/thumbsup.svg
  src/app/reviews/images/review-banner.png
  src/app/reviews/page.tsx
  src/app/reviews/utils/generateProfileBackgroundColor.ts
  src/components/layout/Nav.tsx
  src/services/demand.service.ts
  src/services/event.service.ts
  src/services/review.service.ts
  src/types/demand.type.ts
  src/types/reviews.type.ts
Labels: 🔖 release
